"""
Modern TLS server (educational)

This server requires TLS 1.2 or newer and prints out the negotiated TLS version and cipher.
Run: python3 server_modern.py

It uses a self-signed certificate generated by `generate_certs.sh` in the same directory.
"""

import socket
import ssl
import pathlib

CERT = pathlib.Path(__file__).with_name("cert.pem")
KEY = pathlib.Path(__file__).with_name("key.pem")
HOST = '127.0.0.1'
PORT = 4443


def main():
    if not CERT.exists() or not KEY.exists():
        print("cert.pem/key.pem not found. Run generate_certs.sh in this directory first.")
        return

    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    # Require TLS 1.2+ (modern server)
    try:
        context.minimum_version = ssl.TLSVersion.TLSv1_2
    except AttributeError:
        # Older Python might not have TLSVersion enum; fall back (best-effort)
        pass

    context.load_cert_chain(certfile=str(CERT), keyfile=str(KEY))

    bindsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
    bindsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    bindsock.bind((HOST, PORT))
    bindsock.listen(5)
    print(f"Modern TLS server listening on {HOST}:{PORT} (requires TLS 1.2+)")

    while True:
        newsock, addr = bindsock.accept()
        try:
            with context.wrap_socket(newsock, server_side=True) as ssock:
                print(f"Connection from {addr}")
                # Show negotiated protocol and cipher
                print("Negotiated protocol:", ssock.version())
                print("Cipher:", ssock.cipher())
                data = ssock.recv(4096)
                print("Received (truncated):", data[:200])
                ssock.sendall(b"HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK")
        except ssl.SSLError as e:
            print("SSL error while handling connection:", e)
            newsock.close()


if __name__ == '__main__':
    main()
